### ISSUE TITLE
Normalize paths for windows

### ISSUE THREAD

**Issue by oupala** [superwolff/metalsmith-fingerprint-ignore#4]
In [metalsmith-fingerprint](/christophercliff/metalsmith-fingerprint/), there was a [pull request](/christophercliff/metalsmith-fingerprint/pull/13/) that has never been mergerd until now.

Do you think you can add the content of this pull request to your fork so that it can fully support windows system?

**Comment by ismay** [comment]
Yeah no problem, makes sense since forward slash paths can be used in windows as well. Would you mind recreating the PR for this repo?

Also, it might be better to use https://github.com/sindresorhus/slash for path normalizing. Outsources the path normalizing and handles a couple of edge cases. If you could implement that and add a note to the readme for clarity I'd be happy to merge 👍

**Comment by oupala** [comment]
In fact, it appears that @timfish has already added support of windows in commit 6947b67a86b59fa1f0dbc1709413040d5967cd9a.

Then syntax used is a bit strange, and does not use [slash](https://github.com/sindresorhus/slash) but I tested it and it works.

**Comment by ismay** [comment]
Ah great. Well I'll leave this open as it would be nice to implement it for this lib as well. If you have time for a PR it would definitely still be welcome.

**Comment by flegris-orange** [comment]
A new PR was created #5 to address this issue.

**Comment by ismay** [comment]
Addressed in #5
